# Regresión Logística multiclase
## Ejercicio 11

Se busca predecir si el tipo de fármaco que se debe administrar a un paciente afectado de rinitis alérgica es el habitual o no. Se dispone de información correspondiente a las historias clínicas de pacientes atendidos previamente


### a) 

Numerice los atributos nominales y utilice el archivo **drugs_train.csv** para entrenar un modelo con 5 neuronas que sea capaz de predecir el tipo de fármaco que se debe administrar a un paciente afectado de rinitis alérgica.

In [ ]:
import pandas as pd

DATOS_DIR   = '../../Datos/'
train_data = pd.read_csv(DATOS_DIR + 'drugs_train.csv')

# Codificar columna 'Drug' en one-hot
train_T = pd.get_dummies(train_data["Drug"]).astype(int).to_numpy()
train_X = train_data.drop(columns=["Drug"])

def label_encoding_preprocess_data(data: pd.DataFrame) -> pd.DataFrame:
    NewSeEstiraColumn = pd.get_dummies(
        data['Sex'], prefix='Sex', drop_first=True
    ).astype(int)
    data = pd.concat([NewSeEstiraColumn, data], axis=1)
    data.drop(['Sex'], axis=1, inplace=True)

    Map = {
        "BP": {
            "LOW": 0,
            "NORMAL": 1,
            "HIGH": 2,
        },
        "Cholesterol": {
            "NORMAL": 0,
            "HIGH": 1,
        }
    }
    data.replace(Map, inplace=True)

    return data

train_X = label_encoding_preprocess_data(train_X)
train_X = (train_X - train_X.min()) / (train_X.max() - train_X.min())
train_X = train_X.to_numpy()


[[0 0 1 0 0]
 [0 0 0 0 1]
 [0 0 0 0 1]
 [0 0 1 0 0]
 [0 0 0 0 1]]


### b) 

Luego utilice el archivo **drugs_test.csv** para medir la calidad del modelo.

In [6]:
DATOS_DIR   = '../../Datos/'
test_data = pd.read_csv(DATOS_DIR + 'drugs_test.csv')

test_T = (test_data["Drug"] == "drugY").astype(int).to_numpy()
test_X = test_data.drop(columns=["Drug"])
test_X = label_encoding_preprocess_data(test_X)

/tmp/ipykernel_381283/3430638826.py:28: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace(Map, inplace=True)
