# Parte 2 - Multiperceptrón con Tensorflow/Keras

## Ejercicio 7

Re-implemente el modelo del ejercicio 4 (Balance.csv) utilizando un Multiperceptrón Tensorflow/Keras.  


##### Preprocesamiento

In [ ]:
import pandas as pd
import numpy as np
from sklearn import preprocessing, model_selection

TEST_SIZE = 0.2

DATOS_DIR   = '../../Datos/'
data = pd.read_csv(DATOS_DIR + 'balance-scale.csv', header=None)
binarizer = preprocessing.LabelBinarizer()

X_raw = np.array(data.iloc[:,1:])
Y_raw = np.array(data.iloc[:,0])  

Y_raw = binarizer.fit_transform(Y_raw)
scaler = preprocessing.StandardScaler()
X_raw = scaler.fit_transform(X_raw)

##### Entrenamiento

In [9]:
from tensorflow.keras import Sequential, optimizers
from tensorflow.keras.layers import Dense, Input

ENTRADAS = X_train.shape[1]
OCULTAS = 2
SALIDAS  = Y_train.shape[1]
ACTIVACION = 'tanh'

EPOCHS = 500
BATCH_SIZE = 32
ALPHA = 0.02

modelo = Sequential()
modelo.add(Input(shape=(ENTRADAS,)))
modelo.add(Dense(OCULTAS, activation=ACTIVACION))
modelo.add(Dense(SALIDAS, activation='softmax'))

modelo.summary()

optimizador = optimizers.SGD(learning_rate=ALPHA)
# obtiene la arquitectura para el modelo y lo compila
modelo.compile(optimizer=optimizador, loss='categorical_crossentropy', metrics = ['accuracy'])

history = modelo.fit(x=X_train, y=Y_train, batch_size=BATCH_SIZE, epochs=EPOCHS)

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 3)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19 (76.00 B)

 Trainable params: 19 (76.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.2520 - loss: 1.1925  
Epoch 2/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3000 - loss: 1.1383 
Epoch 3/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3300 - loss: 1.0950 
Epoch 4/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3700 - loss: 1.0615 
Epoch 5/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3940 - loss: 1.0342 
Epoch 6/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4380 - loss: 1.0119 
Epoch 7/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4580 - loss: 0.9937 
Epoch 8/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.4820 - loss: 0.9779 
Epoch 9/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5120 - loss: 0.9643 
Epoch 10/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5300 - loss: 0.9521 
Epoch 11/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5340 - loss: 0.9409 
Epoch 12/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [7]:
from sklearn import metrics

#  ########### Medición del entrenamiento ######################
Y_pred = modelo.predict(X_train)

# "invierte" la transformacion binaria para obtener los nombres de las clases
Y_it = binarizer.inverse_transform(Y_train)
Y_pred_it = binarizer.inverse_transform(Y_pred)

# calculo manual del accuracy
print('Efectividad: %6.2f%%' % (100*(Y_pred_it == Y_it).sum()/len(Y_it)) )

report = metrics.classification_report(Y_it, Y_pred_it)
print("Reporte SkLearn:\n%s" % report)
cm = metrics.confusion_matrix(Y_it, Y_pred_it)
print("Confusion matrix:\n%s" % cm)


16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step 
Efectividad:  90.00%
Reporte SkLearn:
              precision    recall  f1-score   support

           B       0.47      0.17      0.25        41
           L       0.94      0.96      0.95       230
           R       0.89      0.97      0.93       229

    accuracy                           0.90       500
   macro avg       0.76      0.70      0.71       500
weighted avg       0.88      0.90      0.88       500

Confusion matrix:
[[  7  11  23]
 [  6 220   4]
 [  2   4 223]]
