# Parte 2 - Multiperceptrón con Tensorflow/Keras

## Ejercicio 7

Re-implemente el modelo del ejercicio 4 (Balance.csv) utilizando un Multiperceptrón Tensorflow/Keras.  


##### Preprocesamiento

In [7]:
import pandas as pd
import numpy as np
from sklearn import preprocessing, model_selection

TEST_SIZE = 0.2

DATOS_DIR   = '../../Datos/'
data = pd.read_csv(DATOS_DIR + 'balance-scale.csv', header=None)
binarizer = preprocessing.LabelBinarizer()

X_raw = np.array(data.iloc[:,1:])
Y_raw = np.array(data.iloc[:,0])  

Y_raw = binarizer.fit_transform(Y_raw)
scaler = preprocessing.StandardScaler()
X_raw = scaler.fit_transform(X_raw)

X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X_raw, Y_raw, test_size=TEST_SIZE)

##### Entrenamiento

In [8]:
from tensorflow.keras import Sequential, optimizers
from tensorflow.keras.layers import Dense, Input

ENTRADAS = X_train.shape[1]
OCULTAS = 2
SALIDAS  = Y_train.shape[1]
ACTIVACION = 'tanh'

EPOCHS = 500
BATCH_SIZE = 32
ALPHA = 0.02

modelo = Sequential()
modelo.add(Input(shape=(ENTRADAS,)))
modelo.add(Dense(OCULTAS, activation=ACTIVACION))
modelo.add(Dense(SALIDAS, activation='softmax'))

modelo.summary()

optimizador = optimizers.SGD(learning_rate=ALPHA)
modelo.compile(optimizer=optimizador, loss='categorical_crossentropy', metrics = ['accuracy'])

history = modelo.fit(x=X_train, y=Y_train, batch_size=BATCH_SIZE, epochs=EPOCHS)

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │            10 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 3)              │             9 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 19 (76.00 B)

 Trainable params: 19 (76.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - accuracy: 0.2120 - loss: 1.2127  
Epoch 2/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3180 - loss: 1.1340 
Epoch 3/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.3980 - loss: 1.0676 
Epoch 4/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.5520 - loss: 1.0114 
Epoch 5/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6260 - loss: 0.9627 
Epoch 6/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6600 - loss: 0.9202 
Epoch 7/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.6880 - loss: 0.8814 
Epoch 8/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7120 - loss: 0.8467 
Epoch 9/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7160 - loss: 0.8139 
Epoch 10/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7160 - loss: 0.7830 
Epoch 11/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7380 - loss: 0.7536 
Epoch 12/500
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

In [9]:
from sklearn import metrics

#  ########### Medición del entrenamiento ######################
Y_pred = modelo.predict(X_train)

# "invierte" la transformacion binaria para obtener los nombres de las clases
Y_it = binarizer.inverse_transform(Y_train)
Y_pred_it = binarizer.inverse_transform(Y_pred)

# calculo manual del accuracy
print('Efectividad: %6.2f%%' % (100*(Y_pred_it == Y_it).sum()/len(Y_it)) )

report = metrics.classification_report(Y_it, Y_pred_it)
print("Reporte SkLearn:\n%s" % report)
cm = metrics.confusion_matrix(Y_it, Y_pred_it)
print("Confusion matrix:\n%s" % cm)


16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Efectividad:  89.80%
Reporte SkLearn:
              precision    recall  f1-score   support

           B       0.67      0.05      0.09        41
           L       0.90      0.97      0.93       231
           R       0.90      0.98      0.94       228

    accuracy                           0.90       500
   macro avg       0.82      0.67      0.65       500
weighted avg       0.88      0.90      0.87       500

Confusion matrix:
[[  2  21  18]
 [  0 224   7]
 [  1   4 223]]
